# Generated by Django 3.1 on 2020-08-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='imageField',
            field=models.ImageField(upload_to='home/images/'),
        ),
    ]
